In [16]:
import numpy as np
import matplotlib.pyplot as plt
import polars as pl

df = pl.read_csv('../data/raw/aemet_2022.csv')

plt.style.use('seaborn-v0_8-whitegrid')

In [8]:

df.sample(10)

shape: (10, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────────┬──────┐
│ fecha      ┆ indicativo ┆ nombre     ┆ provincia  ┆ … ┆ horaPresMa ┆ presMin ┆ horaPresMi ┆ sol  │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ x          ┆ ---     ┆ n          ┆ ---  │
│ str        ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ str     ┆ ---        ┆ str  │
│            ┆            ┆            ┆            ┆   ┆ str        ┆         ┆ str        ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════════╪══════╡
│ 2022-01-17 ┆ 5704B      ┆ CAZALLA DE ┆ SEVILLA    ┆ … ┆ 11         ┆ 963,1   ┆ 15         ┆ null │
│            ┆            ┆ LA SIERRA  ┆            ┆   ┆            ┆         ┆            ┆      │
│ 2022-04-29 ┆ B569X      ┆ CAPDEPERA  ┆ BALEARES   ┆ … ┆ 10         ┆ 1013,6  ┆ 18         ┆ null │
│ 2022-05-23 ┆ 7261X      ┆ ROJALES    ┆ ALICANTE   ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-05-26 ┆ B603X      ┆ ARTÀ-COLÒN ┆ ILLES      ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│            ┆            ┆ IA DE SANT ┆ BALEARS    ┆   ┆            ┆         ┆            ┆      │
│            ┆            ┆ PERE       ┆            ┆   ┆            ┆         ┆            ┆      │
│ 2022-07-05 ┆ 6069X      ┆ BENAHAVÍS  ┆ MALAGA     ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-08-25 ┆ 8072Y      ┆ BARX       ┆ VALENCIA   ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-09-04 ┆ 2969U      ┆ A GUDIÑA   ┆ OURENSE    ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-10-27 ┆ 1025X      ┆ BEASAIN,   ┆ GIPUZKOA   ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│            ┆            ┆ ARRIARAN   ┆            ┆   ┆            ┆         ┆            ┆      │
│ 2022-10-31 ┆ 1476R      ┆ ROIS,      ┆ A CORUÑA   ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│            ┆            ┆ CASAS DO   ┆            ┆   ┆            ┆         ┆            ┆      │
│            ┆            ┆ PORTO      ┆            ┆   ┆            ┆         ┆            ┆      │
│ 2022-11-14 ┆ 0009X      ┆ ALFORJA    ┆ TARRAGONA  ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────────┴──────┘

In [13]:
df.describe()

shape: (9, 26)
┌────────────┬────────────┬────────────┬──────────┬───┬────────────┬─────────┬────────────┬────────┐
│ statistic  ┆ fecha      ┆ indicativo ┆ nombre   ┆ … ┆ horaPresMa ┆ presMin ┆ horaPresMi ┆ sol    │
│ ---        ┆ ---        ┆ ---        ┆ ---      ┆   ┆ x          ┆ ---     ┆ n          ┆ ---    │
│ str        ┆ str        ┆ str        ┆ str      ┆   ┆ ---        ┆ str     ┆ ---        ┆ str    │
│            ┆            ┆            ┆          ┆   ┆ str        ┆         ┆ str        ┆        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════════╪═════════╪════════════╪════════╡
│ count      ┆ 308185     ┆ 308185     ┆ 308185   ┆ … ┆ 78043      ┆ 78048   ┆ 78034      ┆ 54859  │
│ null_count ┆ 0          ┆ 0          ┆ 0        ┆ … ┆ 230142     ┆ 230137  ┆ 230151     ┆ 253326 │
│ mean       ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ std        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ min        ┆ 2022-01-01 ┆ 0009X      ┆ A CAÑIZA ┆ … ┆ 00         ┆ 1000,0  ┆ 00         ┆ 0,0    │
│ 25%        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ 50%        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ 75%        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ max        ┆ 2022-12-31 ┆ C939T      ┆ ÓLVEGA   ┆ … ┆ Varias     ┆ 999,9   ┆ Varias     ┆ 9,9    │
└────────────┴────────────┴────────────┴──────────┴───┴────────────┴─────────┴────────────┴────────┘

In [14]:
df.schema

Schema([('fecha', String),
        ('indicativo', String),
        ('nombre', String),
        ('provincia', String),
        ('altitud', Int64),
        ('tmed', String),
        ('prec', String),
        ('tmin', String),
        ('horatmin', String),
        ('tmax', String),
        ('horatmax', String),
        ('hrMedia', Int64),
        ('hrMax', Int64),
        ('horaHrMax', String),
        ('hrMin', Int64),
        ('horaHrMin', String),
        ('dir', Int64),
        ('velmedia', String),
        ('racha', String),
        ('horaracha', String),
        ('presMax', String),
        ('horaPresMax', String),
        ('presMin', String),
        ('horaPresMin', String),
        ('sol', String)])

In [15]:
df.glimpse()

Rows: 308185
Columns: 25
$ fecha       <str> '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01'
$ indicativo  <str> '7250C', '0255B', '5612B', '2885K', '8492X', '2182C', '8270X', '4520X', '2918Y', '8293X'
$ nombre      <str> 'ABANILLA', 'SANTA SUSANNA', 'LA RODA DE ANDALUCÍA', 'FRESNO DE SAYAGO', 'ATZENETA DEL MAESTRAT', 'PEDRAZA', 'BICORP', 'FREGENAL DE LA SIERRA', 'EL MAÍLLO', 'XÀTIVA'
$ provincia   <str> 'MURCIA', 'BARCELONA', 'SEVILLA', 'ZAMORA', 'CASTELLON', 'SEGOVIA', 'VALENCIA', 'BADAJOZ', 'SALAMANCA', 'VALENCIA'
$ altitud     <i64> 174, 40, 410, 804, 420, 1107, 305, 586, 1027, 88
$ tmed        <str> '12,1', '10,2', '13,6', '8,6', '14,2', '12,7', '15,2', '13,8', '14,1', '13,4'
$ prec        <str> '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0'
$ tmin        <str> '2,4', '4,7', '5,7', '-0,6', '3,1', '5,6', '5,4', '4,8', '9,4', '3,9'
$ horatmin    <str> '06:05', '05:00', '07:00', '07:37', '04:02', '00:21', '04:31', '06:10', '05:45', '07:30'
$ tmax        <str> '21,8', '15,6', '21,5', '17,9', '25,2', '19,8', '25,1', '22,8', '18,8', '23,0'
$ horatmax    <str> '14:54', '14:10', '14:20', '14:54', '13:36', '13:55', '13:47', '13:57', '12:06', '14:00'
$ hrMedia     <i64> 67, 88, 59, 92, 50, 36, 53, 54, 34, 60
$ hrMax       <i64> 92, 91, 83, 100, 76, 57, 80, 86, 61, 89
$ horaHrMax   <str> 'Varias', 'Varias', '06:50', 'Varias', '01:50', '08:40', '05:40', 'Varias', '00:50', '19:40'
$ hrMin       <i64> 36, 72, 29, 59, 21, 26, 28, 30, 25, 28
$ horaHrMin   <str> '13:00', '14:00', '14:20', '15:00', '14:20', '14:30', '14:00', '14:30', '13:00', '13:50'
$ dir         <i64> null, null, 18, 19, 14, 28, 28, 16, 17, 25
$ velmedia    <str> null, null, '1,9', '1,9', '0,6', '2,2', '0,8', '1,1', '4,4', '1,7'
$ racha       <str> null, null, '9,4', '6,4', '3,3', '5,6', '3,3', '4,7', '11,9', '3,9'
$ horaracha   <str> null, null, '11:50', '22:40', '14:40', '14:30', '17:40', '11:20', '13:50', '07:40'
$ presMax     <str> null, null, '979,8', null, null, null, null, null, null, '1018,4'
$ horaPresMax <str> null, null, '23', null, null, null, null, null, null, '10'
$ presMin     <str> null, null, '977,2', null, null, null, null, null, null, '1015,2'
$ horaPresMin <str> null, null, '05', null, null, null, null, null, null, '15'
$ sol         <str> null, null, null, null, null, null, null, null, null, '8,0'

In [ ]:
df.values_counts()