In [19]:
import numpy as np
import matplotlib.pyplot as plt
import polars as pl

df = pl.read_csv('../data/raw/aemet_2022.csv')

plt.style.use('seaborn-v0_8-whitegrid')

In [20]:
df.shape

(308185, 25)

In [21]:

df.sample(10)

shape: (10, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────────┬──────┐
│ fecha      ┆ indicativo ┆ nombre     ┆ provincia  ┆ … ┆ horaPresMa ┆ presMin ┆ horaPresMi ┆ sol  │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ x          ┆ ---     ┆ n          ┆ ---  │
│ str        ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ str     ┆ ---        ┆ str  │
│            ┆            ┆            ┆            ┆   ┆ str        ┆         ┆ str        ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════════╪══════╡
│ 2022-02-06 ┆ 6050X      ┆ GAUCÍN     ┆ MALAGA     ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-03-12 ┆ 1089U      ┆ RAMALES DE ┆ CANTABRIA  ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│            ┆            ┆ LA         ┆            ┆   ┆            ┆         ┆            ┆      │
│            ┆            ┆ VICTORIA   ┆            ┆   ┆            ┆         ┆            ┆      │
│ 2022-06-21 ┆ 1347T      ┆ BURELA     ┆ LUGO       ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-07-26 ┆ 9495Y      ┆ LECIÑENA   ┆ ZARAGOZA   ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-07-28 ┆ 4064Y      ┆ ALCAZAR DE ┆ CIUDAD     ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│            ┆            ┆ SAN JUAN   ┆ REAL       ┆   ┆            ┆         ┆            ┆      │
│ 2022-09-09 ┆ 4245X      ┆ GUADALUPE  ┆ CACERES    ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-10-06 ┆ 9908X      ┆ LANAJA     ┆ HUESCA     ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-11-15 ┆ 1037X      ┆ LEGAZPI    ┆ GIPUZKOA   ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
│ 2022-12-25 ┆ 5192       ┆ VILLARRODR ┆ JAEN       ┆ … ┆ Varias     ┆ 922,7   ┆ Varias     ┆ 5,9  │
│            ┆            ┆ IGO        ┆            ┆   ┆            ┆         ┆            ┆      │
│ 2022-12-25 ┆ 9647X      ┆ TORÀ       ┆ LLEIDA     ┆ … ┆ null       ┆ null    ┆ null       ┆ null │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────────┴──────┘

In [22]:
df.describe()

shape: (9, 26)
┌────────────┬────────────┬────────────┬──────────┬───┬────────────┬─────────┬────────────┬────────┐
│ statistic  ┆ fecha      ┆ indicativo ┆ nombre   ┆ … ┆ horaPresMa ┆ presMin ┆ horaPresMi ┆ sol    │
│ ---        ┆ ---        ┆ ---        ┆ ---      ┆   ┆ x          ┆ ---     ┆ n          ┆ ---    │
│ str        ┆ str        ┆ str        ┆ str      ┆   ┆ ---        ┆ str     ┆ ---        ┆ str    │
│            ┆            ┆            ┆          ┆   ┆ str        ┆         ┆ str        ┆        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════════╪═════════╪════════════╪════════╡
│ count      ┆ 308185     ┆ 308185     ┆ 308185   ┆ … ┆ 78043      ┆ 78048   ┆ 78034      ┆ 54859  │
│ null_count ┆ 0          ┆ 0          ┆ 0        ┆ … ┆ 230142     ┆ 230137  ┆ 230151     ┆ 253326 │
│ mean       ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ std        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ min        ┆ 2022-01-01 ┆ 0009X      ┆ A CAÑIZA ┆ … ┆ 00         ┆ 1000,0  ┆ 00         ┆ 0,0    │
│ 25%        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ 50%        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ 75%        ┆ null       ┆ null       ┆ null     ┆ … ┆ null       ┆ null    ┆ null       ┆ null   │
│ max        ┆ 2022-12-31 ┆ C939T      ┆ ÓLVEGA   ┆ … ┆ Varias     ┆ 999,9   ┆ Varias     ┆ 9,9    │
└────────────┴────────────┴────────────┴──────────┴───┴────────────┴─────────┴────────────┴────────┘

In [23]:
df.schema

Schema([('fecha', String),
        ('indicativo', String),
        ('nombre', String),
        ('provincia', String),
        ('altitud', Int64),
        ('tmed', String),
        ('prec', String),
        ('tmin', String),
        ('horatmin', String),
        ('tmax', String),
        ('horatmax', String),
        ('hrMedia', Int64),
        ('hrMax', Int64),
        ('horaHrMax', String),
        ('hrMin', Int64),
        ('horaHrMin', String),
        ('dir', Int64),
        ('velmedia', String),
        ('racha', String),
        ('horaracha', String),
        ('presMax', String),
        ('horaPresMax', String),
        ('presMin', String),
        ('horaPresMin', String),
        ('sol', String)])

In [24]:
df.glimpse()

Rows: 308185
Columns: 25
$ fecha       <str> '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01'
$ indicativo  <str> '7250C', '0255B', '5612B', '2885K', '8492X', '2182C', '8270X', '4520X', '2918Y', '8293X'
$ nombre      <str> 'ABANILLA', 'SANTA SUSANNA', 'LA RODA DE ANDALUCÍA', 'FRESNO DE SAYAGO', 'ATZENETA DEL MAESTRAT', 'PEDRAZA', 'BICORP', 'FREGENAL DE LA SIERRA', 'EL MAÍLLO', 'XÀTIVA'
$ provincia   <str> 'MURCIA', 'BARCELONA', 'SEVILLA', 'ZAMORA', 'CASTELLON', 'SEGOVIA', 'VALENCIA', 'BADAJOZ', 'SALAMANCA', 'VALENCIA'
$ altitud     <i64> 174, 40, 410, 804, 420, 1107, 305, 586, 1027, 88
$ tmed        <str> '12,1', '10,2', '13,6', '8,6', '14,2', '12,7', '15,2', '13,8', '14,1', '13,4'
$ prec        <str> '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0', '0,0'
$ tmin        <str> '2,4', '4,7', '5,7', '-0,6', '3,1', '5,6', '5,4', '4,8', '9,4', '3,9'
$ horatmin    <str> '06:05', '05:00', '07:00', '07:37', '04:02', '00:21', '04:31', '06:10', '05:45', '07:30'
$ tmax        <str> '21,8', '15,6', '21,5', '17,9', '25,2', '19,8', '25,1', '22,8', '18,8', '23,0'
$ horatmax    <str> '14:54', '14:10', '14:20', '14:54', '13:36', '13:55', '13:47', '13:57', '12:06', '14:00'
$ hrMedia     <i64> 67, 88, 59, 92, 50, 36, 53, 54, 34, 60
$ hrMax       <i64> 92, 91, 83, 100, 76, 57, 80, 86, 61, 89
$ horaHrMax   <str> 'Varias', 'Varias', '06:50', 'Varias', '01:50', '08:40', '05:40', 'Varias', '00:50', '19:40'
$ hrMin       <i64> 36, 72, 29, 59, 21, 26, 28, 30, 25, 28
$ horaHrMin   <str> '13:00', '14:00', '14:20', '15:00', '14:20', '14:30', '14:00', '14:30', '13:00', '13:50'
$ dir         <i64> null, null, 18, 19, 14, 28, 28, 16, 17, 25
$ velmedia    <str> null, null, '1,9', '1,9', '0,6', '2,2', '0,8', '1,1', '4,4', '1,7'
$ racha       <str> null, null, '9,4', '6,4', '3,3', '5,6', '3,3', '4,7', '11,9', '3,9'
$ horaracha   <str> null, null, '11:50', '22:40', '14:40', '14:30', '17:40', '11:20', '13:50', '07:40'
$ presMax     <str> null, null, '979,8', null, null, null, null, null, null, '1018,4'
$ horaPresMax <str> null, null, '23', null, null, null, null, null, null, '10'
$ presMin     <str> null, null, '977,2', null, null, null, null, null, null, '1015,2'
$ horaPresMin <str> null, null, '05', null, null, null, null, null, null, '15'
$ sol         <str> null, null, null, null, null, null, null, null, null, '8,0'

In [25]:
for col in df.columns:
    print(f"\n=== {col} ===")
    print(df[col].value_counts(sort=True).head(10))

=== fecha ===
shape: (10, 2)
┌────────────┬───────┐
│ fecha      ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ 2022-01-05 ┆ 854   │
│ 2022-01-01 ┆ 853   │
│ 2022-01-07 ┆ 853   │
│ 2022-01-02 ┆ 852   │
│ 2022-01-03 ┆ 852   │
│ 2022-01-04 ┆ 852   │
│ 2022-01-06 ┆ 852   │
│ 2022-01-08 ┆ 852   │
│ 2022-03-11 ┆ 852   │
│ 2022-03-12 ┆ 852   │
└────────────┴───────┘

=== indicativo ===
shape: (10, 2)
┌────────────┬───────┐
│ indicativo ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ 7250C      ┆ 365   │
│ 2885K      ┆ 365   │
│ 2182C      ┆ 365   │
│ 8270X      ┆ 365   │
│ 4520X      ┆ 365   │
│ 2918Y      ┆ 365   │
│ 8293X      ┆ 365   │
│ 2400E      ┆ 365   │
│ C439J      ┆ 365   │
│ 9808X      ┆ 365   │
└────────────┴───────┘

=== nombre ===
shape: (10, 2)
┌───────────────────────┬───────┐
│ nombre                ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ SANTANDER             ┆ 730   │
│ SAN JAVIER AEROPUERTO ┆ 730   │
│ SANTANDER AEROPUERTO  ┆ 730   │
│ FUENCALIENTE          ┆ 730   │
│ OVIEDO                ┆ 730   │
│ CARTAGENA             ┆ 729   │
│ GRANADA BASE AÉREA    ┆ 697   │
│ ABANILLA              ┆ 365   │
│ FRESNO DE SAYAGO      ┆ 365   │
│ PEDRAZA               ┆ 365   │
└───────────────────────┴───────┘

=== provincia ===
shape: (10, 2)
┌───────────────────────┬───────┐
│ provincia             ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ LAS PALMAS            ┆ 13456 │
│ HUESCA                ┆ 10567 │
│ CACERES               ┆ 10567 │
│ MURCIA                ┆ 10517 │
│ STA. CRUZ DE TENERIFE ┆ 10205 │
│ ASTURIAS              ┆ 9076  │
│ ILLES BALEARS         ┆ 8687  │
│ LLEIDA                ┆ 8676  │
│ BARCELONA             ┆ 8498  │
│ BADAJOZ               ┆ 8479  │
└───────────────────────┴───────┘

=== altitud ===
shape: (10, 2)
┌─────────┬───────┐
│ altitud ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 3       ┆ 3551  │
│ 4       ┆ 2547  │
│ 45      ┆ 2547  │
│ 10      ┆ 2184  │
│ 100     ┆ 2180  │
│ 32      ┆ 2180  │
│ 2       ┆ 2178  │
│ 690     ┆ 2165  │
│ 25      ┆ 1825  │
│ 5       ┆ 1825  │
└─────────┴───────┘

=== tmed ===
shape: (10, 2)
┌──────┬───────┐
│ tmed ┆ count │
│ ---  ┆ ---   │
│ str  ┆ u32   │
╞══════╪═══════╡
│ null ┆ 5567  │
│ 12,4 ┆ 2210  │
│ 11,6 ┆ 2206  │
│ 12,8 ┆ 2184  │
│ 12,2 ┆ 2172  │
│ 11,8 ┆ 2170  │
│ 14,0 ┆ 2162  │
│ 13,2 ┆ 2128  │
│ 10,8 ┆ 2125  │
│ 13,4 ┆ 2123  │
└──────┴───────┘

=== prec ===
shape: (10, 2)
┌──────┬────────┐
│ prec ┆ count  │
│ ---  ┆ ---    │
│ str  ┆ u32    │
╞══════╪════════╡
│ 0,0  ┆ 219273 │
│ 0,2  ┆ 10507  │
│ null ┆ 7320   │
│ 0,4  ┆ 5036   │
│ 0,6  ┆ 3774   │
│ 0,8  ┆ 2964   │
│ 1,0  ┆ 2506   │
│ 1,2  ┆ 2210   │
│ 1,4  ┆ 1966   │
│ Ip   ┆ 1898   │
└──────┴────────┘

=== tmin ===
shape: (10, 2)
┌──────┬───────┐
│ tmin ┆ count │
│ ---  ┆ ---   │
│ str  ┆ u32   │
╞══════╪═══════╡
│ null ┆ 5472  │
│ 11,6 ┆ 1628  │
│ 11,8 ┆ 1620  │
│ 13,0 ┆ 1612  │
│ 10,5 ┆ 1609  │
│ 11,2 ┆ 1599  │
│ 9,8  ┆ 1593  │
│ 13,8 ┆ 1591  │
│ 11,0 ┆ 1583  │
│ 12,3 ┆ 1579  │
└──────┴───────┘

=== horatmin ===
shape: (10, 2)
┌──────────┬───────┐
│ horatmin ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ Varias   ┆ 16292 │
│ 23:59    ┆ 11606 │
│ null     ┆ 7144  │
│ 05:00    ┆ 5878  │
│ 06:00    ┆ 5693  │
│ 05:30    ┆ 3952  │
│ 05:40    ┆ 3662  │
│ 05:50    ┆ 3650  │
│ 07:00    ┆ 3585  │
│ 05:20    ┆ 3228  │
└──────────┴───────┘

=== tmax ===
shape: (10, 2)
┌──────┬───────┐
│ tmax ┆ count │
│ ---  ┆ ---   │
│ str  ┆ u32   │
╞══════╪═══════╡
│ null ┆ 5439  │
│ 17,5 ┆ 1449  │
│ 17,0 ┆ 1430  │
│ 16,0 ┆ 1405  │
│ 17,4 ┆ 1399  │
│ 15,2 ┆ 1386  │
│ 17,1 ┆ 1384  │
│ 16,6 ┆ 1384  │
│ 17,6 ┆ 1378  │
│ 15,8 ┆ 1375  │
└──────┴───────┘

=== horatmax ===
shape: (10, 2)
┌──────────┬───────┐
│ horatmax ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ null     ┆ 7021  │
│ 15:00    ┆ 5680  │
│ Varias   ┆ 5653  │
│ 14:00    ┆ 5459  │
│ 14:50    ┆ 4498  │
│ 14:30    ┆ 4324  │
│ 14:40    ┆ 4281  │
│ 13:50    ┆ 4055  │
│ 14:20    ┆ 3912  │
│ 13:40    ┆ 3726  │
└──────────┴───────┘

=== hrMedia ===
shape: (10, 2)
┌─────────┬───────┐
│ hrMedia ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ null    ┆ 10474 │
│ 71      ┆ 6319  │
│ 72      ┆ 6271  │
│ 74      ┆ 6263  │
│ 68      ┆ 6223  │
│ 73      ┆ 6221  │
│ 75      ┆ 6159  │
│ 70      ┆ 6116  │
│ 69      ┆ 6046  │
│ 66      ┆ 6013  │
└─────────┴───────┘

=== hrMax ===
shape: (10, 2)
┌───────┬───────┐
│ hrMax ┆ count │
│ ---   ┆ ---   │
│ i64   ┆ u32   │
╞═══════╪═══════╡
│ 100   ┆ 26940 │
│ 96    ┆ 14800 │
│ 99    ┆ 14712 │
│ 97    ┆ 14670 │
│ 98    ┆ 14261 │
│ 95    ┆ 14256 │
│ null  ┆ 14131 │
│ 94    ┆ 13756 │
│ 93    ┆ 12693 │
│ 92    ┆ 11992 │
└───────┴───────┘

=== horaHrMax ===
shape: (10, 2)
┌───────────┬───────┐
│ horaHrMax ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ Varias    ┆ 95444 │
│ null      ┆ 14203 │
│ 23:59     ┆ 8810  │
│ 00:00     ┆ 7712  │
│ 05:30     ┆ 5787  │
│ 23:50     ┆ 5711  │
│ 05:40     ┆ 5556  │
│ 05:50     ┆ 5211  │
│ 06:00     ┆ 5033  │
│ 06:10     ┆ 4430  │
└───────────┴───────┘

=== hrMin ===
shape: (10, 2)
┌───────┬───────┐
│ hrMin ┆ count │
│ ---   ┆ ---   │
│ i64   ┆ u32   │
╞═══════╪═══════╡
│ null  ┆ 14111 │
│ 50    ┆ 5197  │
│ 32    ┆ 5167  │
│ 46    ┆ 5156  │
│ 34    ┆ 5119  │
│ 35    ┆ 5102  │
│ 33    ┆ 5091  │
│ 52    ┆ 5088  │
│ 45    ┆ 5085  │
│ 36    ┆ 5054  │
└───────┴───────┘

=== horaHrMin ===
shape: (10, 2)
┌───────────┬───────┐
│ horaHrMin ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ Varias    ┆ 29049 │
│ 13:00     ┆ 16344 │
│ null      ┆ 14207 │
│ 14:30     ┆ 7754  │
│ 14:40     ┆ 7331  │
│ 15:00     ┆ 7272  │
│ 14:50     ┆ 7235  │
│ 14:00     ┆ 7047  │
│ 13:50     ┆ 6719  │
│ 14:10     ┆ 6692  │
└───────────┴───────┘

=== dir ===
shape: (10, 2)
┌──────┬───────┐
│ dir  ┆ count │
│ ---  ┆ ---   │
│ i64  ┆ u32   │
╞══════╪═══════╡
│ null ┆ 54459 │
│ 99   ┆ 16309 │
│ 24   ┆ 10317 │
│ 26   ┆ 10167 │
│ 28   ┆ 9952  │
│ 22   ┆ 9635  │
│ 20   ┆ 8468  │
│ 30   ┆ 8324  │
│ 10   ┆ 8260  │
│ 8    ┆ 8192  │
└──────┴───────┘

=== velmedia ===
shape: (10, 2)
┌──────────┬───────┐
│ velmedia ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ null     ┆ 53541 │
│ 1,7      ┆ 22056 │
│ 1,9      ┆ 22035 │
│ 2,2      ┆ 21044 │
│ 1,4      ┆ 20500 │
│ 2,5      ┆ 19049 │
│ 1,1      ┆ 17343 │
│ 2,8      ┆ 16707 │
│ 3,1      ┆ 14380 │
│ 0,8      ┆ 12694 │
└──────────┴───────┘

=== racha ===
shape: (10, 2)
┌───────┬───────┐
│ racha ┆ count │
│ ---   ┆ ---   │
│ str   ┆ u32   │
╞═══════╪═══════╡
│ null  ┆ 54459 │
│ 8,3   ┆ 9758  │
│ 7,8   ┆ 9734  │
│ 8,9   ┆ 9495  │
│ 7,2   ┆ 9409  │
│ 7,5   ┆ 9098  │
│ 9,2   ┆ 9089  │
│ 6,7   ┆ 8727  │
│ 8,6   ┆ 8620  │
│ 9,7   ┆ 8425  │
└───────┴───────┘

=== horaracha ===
shape: (10, 2)
┌───────────┬───────┐
│ horaracha ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ null      ┆ 54474 │
│ Varias    ┆ 15182 │
│ 13:40     ┆ 4740  │
│ 13:30     ┆ 4685  │
│ 14:10     ┆ 4670  │
│ 14:30     ┆ 4620  │
│ 14:00     ┆ 4598  │
│ 14:20     ┆ 4587  │
│ 14:40     ┆ 4566  │
│ 13:50     ┆ 4520  │
└───────────┴───────┘

=== presMax ===
shape: (10, 2)
┌─────────┬────────┐
│ presMax ┆ count  │
│ ---     ┆ ---    │
│ str     ┆ u32    │
╞═════════╪════════╡
│ null    ┆ 230135 │
│ 1014,5  ┆ 235    │
│ 1016,0  ┆ 233    │
│ 1014,0  ┆ 220    │
│ 1014,7  ┆ 220    │
│ 1015,1  ┆ 219    │
│ 1016,6  ┆ 213    │
│ 1014,6  ┆ 213    │
│ 1015,4  ┆ 212    │
│ 1015,9  ┆ 212    │
└─────────┴────────┘

=== horaPresMax ===
shape: (10, 2)
┌─────────────┬────────┐
│ horaPresMax ┆ count  │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 230142 │
│ 00          ┆ 19906  │
│ Varias      ┆ 16436  │
│ 24          ┆ 8311   │
│ 10          ┆ 6552   │
│ 23          ┆ 6534   │
│ 11          ┆ 4343   │
│ 22          ┆ 4119   │
│ 09          ┆ 3334   │
│ 08          ┆ 1942   │
└─────────────┴────────┘

=== presMin ===
shape: (10, 2)
┌─────────┬────────┐
│ presMin ┆ count  │
│ ---     ┆ ---    │
│ str     ┆ u32    │
╞═════════╪════════╡
│ null    ┆ 230137 │
│ 1011,3  ┆ 217    │
│ 1009,6  ┆ 214    │
│ 1012,1  ┆ 212    │
│ 1011,7  ┆ 211    │
│ 1011,5  ┆ 209    │
│ 1012,5  ┆ 209    │
│ 1011,8  ┆ 209    │
│ 1011,2  ┆ 206    │
│ 1012,2  ┆ 202    │
└─────────┴────────┘

=== horaPresMin ===
shape: (10, 2)
┌─────────────┬────────┐
│ horaPresMin ┆ count  │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 230151 │
│ Varias      ┆ 9741   │
│ 17          ┆ 9581   │
│ 16          ┆ 8134   │
│ 18          ┆ 7517   │
│ 24          ┆ 6451   │
│ 04          ┆ 5762   │
│ 15          ┆ 5360   │
│ 00          ┆ 4600   │
│ 03          ┆ 3981   │
└─────────────┴────────┘

=== sol ===
shape: (10, 2)
┌──────┬────────┐
│ sol  ┆ count  │
│ ---  ┆ ---    │
│ str  ┆ u32    │
╞══════╪════════╡
│ null ┆ 253326 │
│ 0,0  ┆ 3129   │
│ 9,1  ┆ 633    │
│ 8,9  ┆ 632    │
│ 9,0  ┆ 630    │
│ 8,6  ┆ 625    │
│ 9,4  ┆ 611    │
│ 8,8  ┆ 605    │
│ 8,7  ┆ 603    │
│ 9,2  ┆ 599    │
└──────┴────────┘

In [26]:
df.select(pl.all().n_unique())

shape: (1, 25)
┌───────┬────────────┬────────┬───────────┬───┬─────────────┬─────────┬─────────────┬─────┐
│ fecha ┆ indicativo ┆ nombre ┆ provincia ┆ … ┆ horaPresMax ┆ presMin ┆ horaPresMin ┆ sol │
│ ---   ┆ ---        ┆ ---    ┆ ---       ┆   ┆ ---         ┆ ---     ┆ ---         ┆ --- │
│ u32   ┆ u32        ┆ u32    ┆ u32       ┆   ┆ u32         ┆ u32     ┆ u32         ┆ u32 │
╞═══════╪════════════╪════════╪═══════════╪═══╪═════════════╪═════════╪═════════════╪═════╡
│ 365   ┆ 865        ┆ 857    ┆ 54        ┆ … ┆ 27          ┆ 2530    ┆ 27          ┆ 152 │
└───────┴────────────┴────────┴───────────┴───┴─────────────┴─────────┴─────────────┴─────┘

In [27]:
df.null_count()

shape: (1, 25)
┌───────┬────────────┬────────┬───────────┬───┬─────────────┬─────────┬─────────────┬────────┐
│ fecha ┆ indicativo ┆ nombre ┆ provincia ┆ … ┆ horaPresMax ┆ presMin ┆ horaPresMin ┆ sol    │
│ ---   ┆ ---        ┆ ---    ┆ ---       ┆   ┆ ---         ┆ ---     ┆ ---         ┆ ---    │
│ u32   ┆ u32        ┆ u32    ┆ u32       ┆   ┆ u32         ┆ u32     ┆ u32         ┆ u32    │
╞═══════╪════════════╪════════╪═══════════╪═══╪═════════════╪═════════╪═════════════╪════════╡
│ 0     ┆ 0          ┆ 0      ┆ 0         ┆ … ┆ 230142      ┆ 230137  ┆ 230151      ┆ 253326 │
└───────┴────────────┴────────┴───────────┴───┴─────────────┴─────────┴─────────────┴────────┘

Total rows 308000 aprox.
    'fecha': 'fecha',
    'tmed': 'temperatura_media',
    'prec': 'precipitacion',
    'tmin': 'temperatura_minima',
    'tmax': 'temperatura_maxima',
    'hrMedia': 'humedad_relativa_media',
    'hrMax': 'humedad_relativa_maxima',
    'hrMin': 'humedad_relativa_minima',
    'velmedia': 'velocidad_viento_media',
    'racha': 'racha_maxima_viento',
    'sol': 'horas_sol'

In [28]:
df = df.drop(["indicativo", "nombre", "horatmin", "horatmax", "horaHrMin", "dir", "horaracha", "horaPresMax", "horaPresMin", "sol"])

In [30]:
df = df.drop(["horaHrMax", "presMax", "presMin"])

In [ ]:
df = df.rename({
    'tmed': 'temperatura_media',
    'prec': 'precipitacion',
    'tmin': 'temperatura_minima',
    'tmax': 'temperatura_maxima',
    'hrMedia': 'humedad_relativa_media',
    'hrMax': 'humedad_relativa_maxima',
    'hrMin': 'humedad_relativa_minima',
    'velmedia': 'velocidad_viento_media',
    'racha': 'racha_maxima_viento',
})

In [34]:
df.null_count()

shape: (1, 12)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ fecha ┆ provincia ┆ altitud ┆ temperatur ┆ … ┆ humedad_re ┆ humedad_re ┆ velocidad_ ┆ racha_maxi │
│ ---   ┆ ---       ┆ ---     ┆ a_media    ┆   ┆ lativa_max ┆ lativa_min ┆ viento_med ┆ ma_viento  │
│ u32   ┆ u32       ┆ u32     ┆ ---        ┆   ┆ ima        ┆ ima        ┆ ia         ┆ ---        │
│       ┆           ┆         ┆ u32        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u32        │
│       ┆           ┆         ┆            ┆   ┆ u32        ┆ u32        ┆ u32        ┆            │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 0         ┆ 0       ┆ 5567       ┆ … ┆ 14131      ┆ 14111      ┆ 53541      ┆ 54459      │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘